<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Postmeta;
class PostmetaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

      $postmetas = array(
        array('id' => '1','post_id' => '1','key' => 'excerpt','value' => 'A chatbot is always available to serve your customer 24/7. A chatbot can save you a lot of time and money by automating repetitive tasks like qualifying leads or answering questions of your customers. By offering instatily response to your customer, your business will build trust and boost conversions and sales.'),
        array('id' => '2','post_id' => '2','key' => 'excerpt','value' => 'No, you only need a email to sign up.'),
        array('id' => '3','post_id' => '3','key' => 'excerpt','value' => 'Yes, If you are unhappy with our service, we offer 30 days money-back guarantee on any plan.'),
        array('id' => '7','post_id' => '5','key' => 'excerpt','value' => '{"facebook":"https:\\/\\/www.facebook.com\\/","twitter":"https:\\/\\/twitter.com\\/","linkedin":"https:\\/\\/linkedin.com\\/"}'),
        array('id' => '8','post_id' => '5','key' => 'description','value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.'),
        array('id' => '9','post_id' => '5','key' => 'preview','value' => '/uploads/demo/team/1694874849C4KyMuZwMxo5Lwmnm9us.jpg'),
        array('id' => '13','post_id' => '7','key' => 'excerpt','value' => '{"facebook":"https:\\/\\/www.facebook.com\\/","twitter":"https:\\/\\/twitter.com\\/","linkedin":"https:\\/\\/linkedin.com\\/"}'),
        array('id' => '14','post_id' => '7','key' => 'description','value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.'),
        array('id' => '15','post_id' => '7','key' => 'preview','value' => '/uploads/demo/team/1694874536f64vPKQDrHsPAEORNrHy.jpg'),
        array('id' => '16','post_id' => '8','key' => 'preview','value' => '/uploads/demo/1692772089qw2qXAZhWBz2IKPUmfZS.jpg'),
        array('id' => '17','post_id' => '8','key' => 'short_description','value' => 'Today we are announcing an update to the way payouts to sellers are handled at Prompt Market, which will come into effect starting Monday, June 26th, 2023.
            The two changes are the introduction of minimum payout amounts, and switching from daily payouts to weekly & monthly payout cycles.'),
        array('id' => '18','post_id' => '8','key' => 'main_description','value' => '<p>Over the past few months, we have received numerous requests to change our current payout system, and many sellers are on one of these new payout schedules already, however with this update everyone will move over.</p><p>We have decided to do this for a number of reasons:</p><ul><li>Stripe, our payment processor, charges a monthly fee per active account, and an additional fee for each payout. With daily payouts, these charges add up quickly. By switching away from many daily payouts of tiny amounts, we significantly reduce these costs.</li><li>For accounting purposes, and reporting income as a seller, it is difficult to tally up many small payouts, and much easier to work with weekly/monthly payouts.</li><li>Switching away from daily payouts helps us better prevent against scams &amp; fraud on our platform.</li></ul><p>As a new seller, you will start on a monthly payout schedule, and once you hit 50 sales, you will have the option to change over to weekly payouts if you wish.</p><p>For people who are currently collectors of digital art, they have a long view on how things will evolve. Understanding the ways that the work of this moment will grow and change as we move onward in time takes perspective. The story of art is a long one.</p><ul><li>Adjust the work/life balance.</li><li>Manage your workspace and organize your desk.</li><li>Keep In touch with your co-workers.</li><li>Get yourself comfortable.</li></ul>'),
        array('id' => '19','post_id' => '8','key' => 'seo','value' => '{"title":"Updates to Payout Cycles & Minimum Payouts","description":"Today we are announcing an update to the way payouts to sellers are handled at Prompt Market, which will come into effect starting Monday, June 26th, 2023.The two changes are the introduction of minimum payout amounts, and switching from daily payouts to weekly & monthly payout cycles.","tags":"prompt, market, payout"}'),
        array('id' => '20','post_id' => '9','key' => 'preview','value' => '/uploads/demo/1692771774585zMj0ZJrEIbQ8cFuq4.jpg'),
        array('id' => '21','post_id' => '9','key' => 'short_description','value' => 'Today we\'re excited to launch a brand new feature to Prompt market: Prompt Bundles! Bundles allow merchants to offer a collection of prompts at a slightly discounted price. In this short blog post, we\'ll explain how bundles work, and how to create your first bundle.'),
        array('id' => '22','post_id' => '9','key' => 'main_description','value' => '<p>The title and description of the bundle will be displayed to potential buyers, in the same way a regular prompt\'s title and description is used.</p><p>The discount is applied to each individual prompt within the bundle.</p><p>The following restrictions apply to creating bundles:</p><ul><li>Titles can include no special characters</li><li>Titles are limited to 40 characters</li><li>Descriptions are limited to 200 characters</li><li>Discounts can be 5%, 10%, 15%, 20%, or 25%</li><li>Bundles must include at least 2 prompts</li><li>All prompts included in the bundle must be in an \'Approved\' state</li><li>A prompt can only be in one bundle at a time</li></ul><p>In addition to this, there are separate limits on the maximum number of prompts that can be included in a bundle. This is determined by your number of sales, and is viewable in your collections tab<a href="https://promptbase.com/account?view=perks">.</a></p><ul><li><strong>25 sales: </strong>Maximum of 2 prompts per bundle</li><li><strong>75 sales: </strong>Maximum of 3 prompts per bundle</li><li><strong>125 sales: </strong>Maximum of 4 prompts per bundle</li></ul>'),
        array('id' => '23','post_id' => '9','key' => 'seo','value' => '{"title":"Exploring the layers of who\'s the Controller now?","description":"In the competitive business landscape, if there\\u2019s one thing that has led to the massive growth of internet businesses, it is digital advertising. The $600 billion industry holds an outsized control on customers\\u2014- who buys what and thus to the fortunes of these businesses. An interesting aspect of digital advertising is its dynamic and ever-evolving nature, from search ads to video and voice search with the latest being Click to Chat ads. Click to Chat ads, although at a nascent stage currently,","tags":"wa, whatsapp, devstation, wasender, whatsserve"}'),
        array('id' => '24','post_id' => '10','key' => 'preview','value' => '/uploads/demo/1692771754iXwl7aQuXBdTG7rJpvRF.jpg'),
        array('id' => '25','post_id' => '10','key' => 'short_description','value' => 'ChatGPT (Conversational Generative Pre-trained Transformer) is a newly released open-source conversational AI platform. It has been praised for its ability to generate natural language responses to user inputs, and many have hailed it as the next step in creating more human-like conversations. However, despite its promise, certain limitations still prevent it from being a viable replacement for other conversational AI platforms. Let’s explore these limitations and how they can be addressed.'),
        array('id' => '26','post_id' => '10','key' => 'main_description','value' => '<p>The title and description of the bundle will be displayed to potential buyers, in the same way a regular prompt\'s title and description is used.</p><p>The discount is applied to each individual prompt within the bundle.</p><p>The following restrictions apply to creating bundles:</p><ul><li>Titles can include no special characters</li><li>Titles are limited to 40 characters</li><li>Descriptions are limited to 200 characters</li><li>Discounts can be 5%, 10%, 15%, 20%, or 25%</li><li>Bundles must include at least 2 prompts</li><li>All prompts included in the bundle must be in an \'Approved\' state</li><li>A prompt can only be in one bundle at a time</li></ul><p>In addition to this, there are separate limits on the maximum number of prompts that can be included in a bundle. This is determined by your number of sales, and is viewable in your collections tab<a href="https://promptbase.com/account?view=perks">.</a></p><ul><li><strong>25 sales: </strong>Maximum of 2 prompts per bundle</li><li><strong>75 sales: </strong>Maximum of 3 prompts per bundle</li><li><strong>125 sales: </strong>Maximum of 4 prompts per bundle</li></ul>'),
        array('id' => '27','post_id' => '10','key' => 'seo','value' => '{"title":"On abuse of power and power Of the Collective","description":"ChatGPT (Conversational Generative Pre-trained Transformer) is a newly released open-source conversational AI platform. It has been praised for its ability to generate natural language responses to user inputs, and many have hailed it as the next step in creating more human-like conversations. However, despite its promise, certain limitations still prevent it from being a viable replacement for other conversational AI platforms. Let\\u2019s explore these limitations and how they can be addressed.","tags":"wa, whatsapp, devstation, qserve, whatsserve"}'),
        array('id' => '30','post_id' => '12','key' => 'excerpt','value' => 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.'),
        array('id' => '31','post_id' => '12','key' => 'preview','value' => '/uploads/23/03/1678130604XsBOBA2JdT4D3dUMsVPO.jpg'),
        array('id' => '32','post_id' => '13','key' => 'excerpt','value' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum'),
        array('id' => '33','post_id' => '13','key' => 'preview','value' => '/uploads/23/03/1678130652BHfP85klZ25vaXpBU6AT.jpg'),
        array('id' => '34','post_id' => '14','key' => 'excerpt','value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s'),
        array('id' => '35','post_id' => '14','key' => 'preview','value' => '/uploads/23/03/1678130699E0RrnxKNI6tkb6Qc1eV1.jpg'),
        array('id' => '36','post_id' => '15','key' => 'excerpt','value' => 'Boost digital finance adoption with instant balance inquiries, portfolio recommendations, hassle-free claims settlement, cross-sell and more'),
        array('id' => '37','post_id' => '16','key' => 'excerpt','value' => 'Revolutionize your restaurant operations with WhatsApp-based ordering, meal and add-on recommendations, payments and real-time delivery updates'),
        array('id' => '46','post_id' => '19','key' => 'excerpt','value' => 'Explore Prompt commands by talented artists from around the world.'),
        array('id' => '47','post_id' => '19','key' => 'main_description','value' => 'Explore beautiful digital art by talented artists from around the world.'),
        array('id' => '48','post_id' => '19','key' => 'preview','value' => '/uploads/features-icon-3.png'),
        array('id' => '49','post_id' => '19','key' => 'banner','value' => '/uploads/23/03/1678178152NI8xZNWqa96WzC13Aytg.gif'),
        array('id' => '50','post_id' => '20','key' => 'excerpt','value' => 'Easily buy and sell your Prompt in the largest marketplace.'),
        array('id' => '51','post_id' => '20','key' => 'main_description','value' => 'Easily buy and sell your NFTs in the largest marketplace.'),
        array('id' => '52','post_id' => '20','key' => 'preview','value' => '/uploads/features-icon-4.png'),
        array('id' => '53','post_id' => '20','key' => 'banner','value' => '/uploads/23/03/16781761667IC0JxTR0A4nDQ3pPkPn.webp'),
        array('id' => '54','post_id' => '21','key' => 'excerpt','value' => 'Get paid by selling Prompts with secured payment methods.'),
        array('id' => '55','post_id' => '21','key' => 'main_description','value' => 'Research similar prompts on the marketplace to determine competitive pricing. Strike a balance between attracting buyers and earning a fair profit.'),
        array('id' => '56','post_id' => '21','key' => 'preview','value' => '/uploads/features-icon-2.png'),
        array('id' => '57','post_id' => '21','key' => 'banner','value' => '/uploads/23/03/1678177795QbOsO2mocgkgO8NRF071.png'),
        array('id' => '58','post_id' => '22','key' => 'excerpt','value' => 'Once you’ve set up your wallet of choice, connect.'),
        array('id' => '59','post_id' => '22','key' => 'main_description','value' => 'Start by crafting captivating and original prompts that cater to various creative interests and industries. Ensure they are concise, engaging, and unique, appealing to potential buyers.'),
        array('id' => '60','post_id' => '22','key' => 'preview','value' => '/uploads/features-icon-1.png'),
        array('id' => '61','post_id' => '22','key' => 'banner','value' => '/uploads/23/03/16781773587loKRma922J59f5EOXHQ.png'),
        array('id' => '62','post_id' => '23','key' => 'excerpt','value' => 'Prompt Market is the best quaint james bond victoria sponge happy days cras.'),
        array('id' => '63','post_id' => '24','key' => 'excerpt','value' => 'No you can simply register with your email'),
        array('id' => '64','post_id' => '25','key' => 'excerpt  pt','value' => 'Prompt Market has supported free 10 days trial. You don\'t need to add credit card information.'),
        array('id' => '65','post_id' => '26','key' => 'description','value' => 'What is Lorem Ipsum?
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
            
            Why do we use it?
            It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).'),
        array('id' => '66','post_id' => '26','key' => 'seo','value' => '{"title":"terms and conditions","description":"orem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, w","tags":"wa, whatsapp, devstation, qserve, whatsserve"}'),
       
        array('id' => '69','post_id' => '28','key' => 'excerpt','value' => '{"facebook":"https:\\/\\/www.facebook.com\\/","twitter":"https:\\/\\/twitter.com\\/","linkedin":"https:\\/\\/linkedin.com\\/"}'),
        array('id' => '70','post_id' => '28','key' => 'description','value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s'),
        array('id' => '71','post_id' => '28','key' => 'preview','value' => '/uploads/demo/team/16948747308CLfioqdGL9sBj2o83TD.jpg'),
        array('id' => '72','post_id' => '29','key' => 'excerpt','value' => '{"facebook":"https:\\/\\/www.facebook.com\\/","twitter":"https:\\/\\/twitter.com\\/","linkedin":"https:\\/\\/linkedin.com\\/"}'),
        array('id' => '73','post_id' => '29','key' => 'description','value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s'),
        array('id' => '74','post_id' => '29','key' => 'preview','value' => '/uploads/demo/team/1694876205MHlmkvNpLaIArb17WCX3.jpg'),
        array('id' => '75','post_id' => '30','key' => 'excerpt','value' => '{"facebook":"https:\\/\\/www.facebook.com\\/","twitter":"https:\\/\\/twitter.com\\/","linkedin":"https:\\/\\/linkedin.com\\/"}'),
        array('id' => '76','post_id' => '30','key' => 'description','value' => 'UI Designer'),
        array('id' => '77','post_id' => '30','key' => 'preview','value' => '/uploads/demo/team/16948763233x7CJI7d1BBxxqG5iKSQ.jpg'),
        array('id' => '78','post_id' => '27','key' => 'description','value' => 'What is Lorem Ipsum?
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
        
        Why do we use it?
        It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).'),
    array('id' => '79','post_id' => '27','key' => 'seo','value' => '{"title":"Privacy policy","description":"orem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, w","tags":"wa, whatsapp, devstation, qserve, whatsserve"}'),
      );

      Postmeta::insert($postmetas);
    }
}
